CREATE TABLE songs (
    id SERIAL PRIMARY KEY, 
    name TEXT NOT NULL,
    artist TEXT,
    album TEXT,
    time TEXT,
    is_favorite BOOLEAN
);

alter table songs add CONSTRAINT uc_songs_unique_combination UNIQUE (name, artist, album);

insert into songs (name, artist, album, time, is_favorite) values ('Slimspike Windmill Grass', 'Lizzo', 'Mystic Moonlight', '04:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Arching Sedge', 'Tame Impala', 'Ethereal Echoes', '05:03', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Texasgrass', 'Tame Impala', 'Whimsical Wanderlust', '08:44', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Three-lobe Violet', 'Tame Impala', 'Ethereal Echoes', '05:29', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Smallflower Phacelia', 'Tame Impala', 'Whimsical Wanderlust', '03:33', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Wart Lichen', 'Alt-J', 'Mystic Moonlight', '08:33', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Limestone Spleenwort', 'Alt-J', 'Whimsical Wanderlust', '07:19', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Chaparral Nightshade', 'Hozier', 'Wander', '03:47', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Eared Veinfern', 'Hozier', 'Wander', '03:44', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Dancing-lady Orchid', 'Aurora', 'Wander', '07:44', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pitaya', 'Lizzo', 'Whimsical Wanderlust', '04:36', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Denseleaf Draba', 'Alt-J', 'Mystic Moonlight', '09:26', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Purple Deadnettle', 'Tame Impala', 'Ethereal Echoes', '05:12', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Smallflower Deathcamas', 'Lizzo', 'Ethereal Echoes', '04:16', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Mountain Phacelia', 'Hozier', 'Wander', '08:37', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('European Heliotrope', 'Hozier', 'Ethereal Echoes', '08:30', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Yellow Marsh Saxifrage', 'Lizzo', 'Mystic Moonlight', '09:10', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Thicket Hogwood', 'Aurora', 'Whimsical Wanderlust', '07:50', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Mountain Barley', 'Aurora', 'Ethereal Echoes', '05:05', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Coastal Wattle', 'Hozier', 'Whimsical Wanderlust', '06:40', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Butte Desertparsley', 'Lizzo', 'Mystic Moonlight', '02:27', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Parry''s Jujube', 'Aurora', 'Whimsical Wanderlust', '02:36', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Tucson Cracked Lichen', 'Tame Impala', 'Ethereal Echoes', '04:20', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Walpole''s Poppy', 'Aurora', 'Wander', '09:34', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Neglected Sunflower', 'Aurora', 'Wander', '03:44', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Golden Linanthus', 'Tame Impala', 'Ethereal Echoes', '06:13', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Davy''s Sedge', 'Hozier', 'Mystic Moonlight', '08:32', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Squarestem Butterflybush', 'Lizzo', 'Ethereal Echoes', '03:40', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Mountain Blue-eyed Grass', 'Aurora', 'Whimsical Wanderlust', '08:19', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sharpglume Brome', 'Hozier', 'Whimsical Wanderlust', '08:06', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Slender Buckwheat', 'Tame Impala', 'Whimsical Wanderlust', '09:10', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Ridgetop Schiedea', 'Aurora', 'Ethereal Echoes', '08:03', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pinefoot', 'Lizzo', 'Ethereal Echoes', '09:26', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Flowers'' Rim Lichen', 'Alt-J', 'Whimsical Wanderlust', '09:08', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Flor De Pasmo', 'Tame Impala', 'Ethereal Echoes', '04:20', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Smooth False Buttonweed', 'Aurora', 'Whimsical Wanderlust', '04:20', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Coastal Pricklypear', 'Alt-J', 'Whimsical Wanderlust', '02:50', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Handsome Pussy-toes', 'Lizzo', 'Mystic Moonlight', '09:34', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Roughglume Bushy Bluestem', 'Lizzo', 'Whimsical Wanderlust', '09:18', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Alpine False Candytuft', 'Hozier', 'Wander', '07:37', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Cooper''s Popcornflower', 'Lizzo', 'Whimsical Wanderlust', '08:16', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Orange Lichen', 'Tame Impala', 'Ethereal Echoes', '08:59', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('White Sagebrush', 'Hozier', 'Whimsical Wanderlust', '07:23', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Common Persimmon', 'Lizzo', 'Mystic Moonlight', '03:48', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Zion Draba', 'Hozier', 'Wander', '07:03', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Rubber Rabbitbrush', 'Tame Impala', 'Mystic Moonlight', '06:59', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Goldenbush', 'Hozier', 'Ethereal Echoes', '06:25', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Bogrush', 'Hozier', 'Mystic Moonlight', '06:07', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('California Larkspur', 'Alt-J', 'Whimsical Wanderlust', '04:54', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pinkhead Smartweed', 'Lizzo', 'Ethereal Echoes', '05:19', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Ribbed False Pennyroyal', 'Hozier', 'Whimsical Wanderlust', '05:06', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Wreath Lichen', 'Hozier', 'Whimsical Wanderlust', '06:14', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Rocky Mountain Dwarf-primrose', 'Alt-J', 'Ethereal Echoes', '07:08', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Largeflowered Fiddleneck', 'Tame Impala', 'Whimsical Wanderlust', '09:51', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Fivespot', 'Aurora', 'Wander', '03:48', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Bigleaf Periwinkle', 'Aurora', 'Mystic Moonlight', '09:16', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Plumed Clover', 'Tame Impala', 'Mystic Moonlight', '09:53', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Softstem Bulrush', 'Hozier', 'Whimsical Wanderlust', '09:18', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pucciphippsia', 'Alt-J', 'Whimsical Wanderlust', '02:36', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Showy Colchicum', 'Lizzo', 'Mystic Moonlight', '07:12', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Mojave Indigobush', 'Tame Impala', 'Whimsical Wanderlust', '09:20', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Shining False Indigo', 'Aurora', 'Ethereal Echoes', '05:03', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Granadillo Bobo', 'Lizzo', 'Whimsical Wanderlust', '08:34', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Threeleaf Shrubverbena', 'Aurora', 'Ethereal Echoes', '09:07', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Chaplin''s Golden Columbine', 'Lizzo', 'Ethereal Echoes', '02:27', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Stinking Goosefoot', 'Hozier', 'Wander', '09:04', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Lempholemma Lichen', 'Alt-J', 'Mystic Moonlight', '04:55', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Parish Lipfern', 'Lizzo', 'Wander', '08:52', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Naranjilla', 'Lizzo', 'Mystic Moonlight', '04:37', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Maidenhair Creeper', 'Lizzo', 'Mystic Moonlight', '03:12', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Hampton False Foxglove', 'Lizzo', 'Mystic Moonlight', '07:44', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Limestone Draba', 'Lizzo', 'Ethereal Echoes', '07:03', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Swamp Flatsedge', 'Alt-J', 'Wander', '05:03', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Guadalupe Cryptantha', 'Tame Impala', 'Wander', '02:28', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pyrenocollema Lichen', 'Alt-J', 'Mystic Moonlight', '06:38', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Wallaby Grass', 'Hozier', 'Ethereal Echoes', '07:19', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Polytrichum Moss', 'Lizzo', 'Wander', '08:54', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Spilanthes', 'Alt-J', 'Wander', '06:14', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Disk Lichen', 'Alt-J', 'Ethereal Echoes', '05:32', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sierra Marsh Fern', 'Tame Impala', 'Whimsical Wanderlust', '08:33', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Texas Jelly Lichen', 'Aurora', 'Mystic Moonlight', '09:20', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Aleppo Pine', 'Tame Impala', 'Wander', '04:16', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('White Prairie Aster', 'Tame Impala', 'Wander', '02:29', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Abrojo Colorado', 'Tame Impala', 'Ethereal Echoes', '07:38', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Peach Palm', 'Alt-J', 'Wander', '04:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Cottony Goldenaster', 'Alt-J', 'Whimsical Wanderlust', '07:23', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Maroonspot Calicoflower', 'Lizzo', 'Whimsical Wanderlust', '06:38', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Havana Clustervine', 'Alt-J', 'Whimsical Wanderlust', '03:46', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('English Peak Greenbrier', 'Alt-J', 'Whimsical Wanderlust', '07:19', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Buckwheat', 'Lizzo', 'Mystic Moonlight', '03:07', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Coastal Sandmat', 'Lizzo', 'Ethereal Echoes', '02:32', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Brandegee''s Four-nerve Daisy', 'Aurora', 'Whimsical Wanderlust', '03:48', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Hibiscus', 'Alt-J', 'Whimsical Wanderlust', '06:38', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sweet-amber', 'Aurora', 'Whimsical Wanderlust', '02:53', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Red Bluff Dwarf Rush', 'Aurora', 'Whimsical Wanderlust', '02:53', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Woolly Breeches', 'Lizzo', 'Mystic Moonlight', '02:53', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Flatsedge', 'Lizzo', 'Mystic Moonlight', '05:19', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Eucalyptus', 'Aurora', 'Whimsical Wanderlust', '05:53', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Orange Lichen', 'Hozier', 'Whimsical Wanderlust', '04:15', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Wiry Snapdragon', 'Hozier', 'Whimsical Wanderlust', '04:16', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Trichostomum Moss', 'Tame Impala', 'Whimsical Wanderlust', '03:23', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Athel Tamarisk', 'Hozier', 'Wander', '05:02', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Distichium Moss', 'Hozier', 'Whimsical Wanderlust', '03:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sand Verbena', 'Hozier', 'Mystic Moonlight', '09:46', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('California Goldenbush', 'Aurora', 'Wander', '08:06', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Rosette Lichen', 'Tame Impala', 'Ethereal Echoes', '07:23', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Large Knotgrass', 'Tame Impala', 'Ethereal Echoes', '07:06', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Thurber''s Penstemon', 'Aurora', 'Whimsical Wanderlust', '06:14', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Northern Groundcone', 'Alt-J', 'Whimsical Wanderlust', '09:46', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Trophis', 'Aurora', 'Ethereal Echoes', '06:40', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Dog''s-tongue', 'Lizzo', 'Ethereal Echoes', '04:07', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Spanish Thyme', 'Hozier', 'Whimsical Wanderlust', '08:23', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Prickly Clover', 'Lizzo', 'Whimsical Wanderlust', '07:50', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Woolly Marsh Elder', 'Hozier', 'Mystic Moonlight', '03:18', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Treetrunk Cyanea', 'Aurora', 'Wander', '03:40', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Donnellia Moss', 'Tame Impala', 'Whimsical Wanderlust', '09:04', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Chapman''s Yelloweyed Grass', 'Tame Impala', 'Whimsical Wanderlust', '04:59', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Redscale Shoestring Fern', 'Hozier', 'Ethereal Echoes', '07:12', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Owyhee Clover', 'Hozier', 'Mystic Moonlight', '07:54', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pinyon Beardtongue', 'Lizzo', 'Ethereal Echoes', '09:35', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Waimakanui', 'Alt-J', 'Ethereal Echoes', '06:59', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('California Zahlbrucknerella Lichen', 'Alt-J', 'Ethereal Echoes', '06:14', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Bog Dewberry', 'Tame Impala', 'Mystic Moonlight', '07:42', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Bunch Cutgrass', 'Aurora', 'Ethereal Echoes', '05:32', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('San Benito Thorn-mint', 'Tame Impala', 'Wander', '08:54', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Hairy Nutrush', 'Lizzo', 'Ethereal Echoes', '09:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Homalothecium Moss', 'Aurora', 'Ethereal Echoes', '06:13', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sierra Cryptantha', 'Tame Impala', 'Whimsical Wanderlust', '03:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Cyrtandra', 'Lizzo', 'Mystic Moonlight', '05:37', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Spiny Fameflower', 'Alt-J', 'Whimsical Wanderlust', '08:34', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Entireleaf Mountain-avens', 'Aurora', 'Mystic Moonlight', '05:16', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pinewoods Rose Gentian', 'Lizzo', 'Mystic Moonlight', '04:20', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Mexican Prairie Clover', 'Alt-J', 'Whimsical Wanderlust', '06:48', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Berlandier''s Wolfberry', 'Hozier', 'Whimsical Wanderlust', '08:54', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Pore Lichen', 'Tame Impala', 'Mystic Moonlight', '07:05', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Thickleaf Water-willow', 'Lizzo', 'Whimsical Wanderlust', '04:35', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Dogwoodleaf', 'Alt-J', 'Mystic Moonlight', '05:03', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Sneezeweed', 'Aurora', 'Wander', '09:37', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Manyflower Tobacco', 'Aurora', 'Whimsical Wanderlust', '02:10', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Asian Melastome', 'Aurora', 'Mystic Moonlight', '04:36', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Oleander Fern', 'Tame Impala', 'Mystic Moonlight', '06:10', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Carolina Horsenettle', 'Tame Impala', 'Ethereal Echoes', '05:03', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Weed''s Mariposa Lily', 'Lizzo', 'Ethereal Echoes', '07:47', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('New Mexico Maple', 'Hozier', 'Ethereal Echoes', '03:48', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Dust Lichen', 'Tame Impala', 'Mystic Moonlight', '05:13', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Attalea Palm', 'Aurora', 'Mystic Moonlight', '02:29', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Goodding''s Willow', 'Lizzo', 'Wander', '09:47', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Tundra Warnstorfia Moss', 'Aurora', 'Wander', '06:18', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Isopterygiopsis Moss', 'Aurora', 'Whimsical Wanderlust', '02:53', true) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Showy Penstemon', 'Hozier', 'Mystic Moonlight', '02:58', false) on conflict (name, artist, album) do nothing;
insert into songs (name, artist, album, time, is_favorite) values ('Prairiedawn', 'Arctic Monkeys', 'Ephemeral Dreams', '03:16', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Small Bonny Bellflower', 'Kendrick Lamar', 'Midnight Melodies', '02:27', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sedge', 'Kendrick Lamar', 'Enchanted Journey', '09:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tasmanian Bluegum', 'Adele', 'Midnight Melodies', '04:58', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Dollar Orchid', 'The Weeknd', 'Serendipity Rhapsody', '02:55', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Gelatinous Skin Lichen', 'Adele', 'Midnight Melodies', '06:22', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Rambling Dewberry', 'Beyoncé', 'Midnight Melodies', '02:53', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Park Rockcress', 'Beyoncé', 'Enchanted Journey', '09:42', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('False Waterwillow', 'Arctic Monkeys', 'Serendipity Rhapsody', '02:47', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Purple Sage', 'The Weeknd', 'Serendipity Rhapsody', '07:12', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('St. John''s Rosemallow', 'Kendrick Lamar', 'Midnight Melodies', '09:42', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Bartramidula Moss', 'The Weeknd', 'Serendipity Rhapsody', '05:50', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Rock Clematis', 'Kendrick Lamar', 'Harmonic Whispers', '07:06', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Pickleweed', 'Kendrick Lamar', 'Midnight Melodies', '08:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Netvein Goldeneye', 'Beyoncé', 'Enchanted Journey', '09:47', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Roell''s Moss', 'The Weeknd', 'Ephemeral Dreams', '02:26', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Southern Magnolia', 'The Weeknd', 'Ephemeral Dreams', '05:28', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Napali Beach Starviolet', 'Arctic Monkeys', 'Harmonic Whispers', '06:46', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Black Spleenwort', 'Kendrick Lamar', 'Serendipity Rhapsody', '08:33', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Dimeresia', 'Adele', 'Enchanted Journey', '03:57', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tahoe Sedge', 'Beyoncé', 'Enchanted Journey', '08:01', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Manystem Ratany', 'Adele', 'Ephemeral Dreams', '04:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Palmer''s Breadroot', 'Arctic Monkeys', 'Harmonic Whispers', '04:57', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('White Moneywort', 'Adele', 'Midnight Melodies', '09:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Lichenostigma Lichen', 'Beyoncé', 'Harmonic Whispers', '03:46', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Agrestia Lichen', 'Beyoncé', 'Harmonic Whispers', '05:29', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Elephantear Pricklypear', 'Beyoncé', 'Enchanted Journey', '03:12', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Okenia', 'Kendrick Lamar', 'Enchanted Journey', '07:51', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Dwarf Popcornflower', 'Arctic Monkeys', 'Ephemeral Dreams', '02:36', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Asian Spikemoss', 'Kendrick Lamar', 'Enchanted Journey', '09:42', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Rocky Mountain Phlox', 'Beyoncé', 'Celestial Serenade', '03:02', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Lecidella Lichen', 'Kendrick Lamar', 'Midnight Melodies', '07:11', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Italian Cornsalad', 'Kendrick Lamar', 'Enchanted Journey', '06:22', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sunbright', 'The Weeknd', 'Harmonic Whispers', '09:57', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Yellowdome', 'Adele', 'Serendipity Rhapsody', '02:48', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Spleenwort', 'The Weeknd', 'Celestial Serenade', '07:54', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Scouringrush Horsetail', 'Kendrick Lamar', 'Celestial Serenade', '09:54', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Myagrum', 'Kendrick Lamar', 'Serendipity Rhapsody', '09:15', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Matted Grama', 'The Weeknd', 'Midnight Melodies', '09:10', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Southern Twayblade', 'The Weeknd', 'Harmonic Whispers', '04:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Ethiopian Rattlebox', 'Adele', 'Harmonic Whispers', '06:38', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Prickly Bog Sedge', 'The Weeknd', 'Ephemeral Dreams', '08:33', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Ponce Beadfern', 'Arctic Monkeys', 'Ephemeral Dreams', '05:14', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Oahu Aiea', 'The Weeknd', 'Celestial Serenade', '09:34', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Wright''s Trumpets', 'Adele', 'Harmonic Whispers', '06:50', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Psilolechia Lichen', 'The Weeknd', 'Enchanted Journey', '06:51', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Green Medusa Orchid', 'The Weeknd', 'Enchanted Journey', '07:19', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Garber''s Blazing Star', 'Adele', 'Harmonic Whispers', '03:16', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Grundlach''s Attorney', 'Beyoncé', 'Enchanted Journey', '08:52', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Pleuroziopsis Moss', 'Adele', 'Ephemeral Dreams', '07:20', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Leichhardt''s Datura', 'The Weeknd', 'Midnight Melodies', '07:47', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Koolau Range Cyrtandra', 'Arctic Monkeys', 'Harmonic Whispers', '09:34', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Smallawned Sedge', 'The Weeknd', 'Ephemeral Dreams', '07:20', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Stiff Phlox', 'Adele', 'Serendipity Rhapsody', '08:01', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Alabama Serviceberry', 'The Weeknd', 'Midnight Melodies', '02:32', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Eastwood''s Manzanita', 'Adele', 'Enchanted Journey', '09:11', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Roundleaf Goldenrod', 'Beyoncé', 'Ephemeral Dreams', '07:19', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Redskin Onion', 'Adele', 'Enchanted Journey', '08:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tidalmarsh Amaranth', 'The Weeknd', 'Midnight Melodies', '05:32', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hooded Orchid', 'Adele', 'Midnight Melodies', '08:14', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Crimson Bottlebrush', 'Arctic Monkeys', 'Enchanted Journey', '04:16', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Pannewitz''s Sedge', 'Arctic Monkeys', 'Ephemeral Dreams', '04:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Jones'' Tidytips', 'Kendrick Lamar', 'Midnight Melodies', '06:01', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Corkbark Fir', 'Arctic Monkeys', 'Enchanted Journey', '02:40', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Krog''s Tube Lichen', 'Beyoncé', 'Enchanted Journey', '08:14', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Canadian Wildrye', 'Adele', 'Serendipity Rhapsody', '06:38', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Plantain Lily', 'The Weeknd', 'Celestial Serenade', '06:53', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Indiantree Spurge', 'Kendrick Lamar', 'Serendipity Rhapsody', '09:20', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Shieldplant', 'Kendrick Lamar', 'Ephemeral Dreams', '08:37', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Lindsaeosoria', 'The Weeknd', 'Celestial Serenade', '08:37', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Coon''s Tail', 'Adele', 'Ephemeral Dreams', '09:11', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Peperomia', 'Adele', 'Harmonic Whispers', '09:53', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Pineland Nerveray', 'Adele', 'Celestial Serenade', '07:06', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hybrid Oak', 'Kendrick Lamar', 'Enchanted Journey', '07:54', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Gracilariopsis', 'Adele', 'Enchanted Journey', '05:03', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Custer Milkvetch', 'The Weeknd', 'Celestial Serenade', '03:37', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tilesius'' Wormwood', 'The Weeknd', 'Harmonic Whispers', '08:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Koehler''s Rockcress', 'The Weeknd', 'Midnight Melodies', '05:05', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Western Poppy', 'Adele', 'Midnight Melodies', '09:18', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Shrubby Woodsorrel', 'Adele', 'Harmonic Whispers', '09:15', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Eastern Gray Beardtongue', 'Adele', 'Serendipity Rhapsody', '02:26', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sand Ryegrass', 'Kendrick Lamar', 'Harmonic Whispers', '09:20', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Bog Birch', 'Beyoncé', 'Celestial Serenade', '08:44', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('American Vetch', 'Arctic Monkeys', 'Celestial Serenade', '04:09', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Riedle''s Nightshade', 'Kendrick Lamar', 'Celestial Serenade', '08:52', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Alpine Willow', 'Kendrick Lamar', 'Ephemeral Dreams', '07:23', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Lindsay''s Map Lichen', 'Adele', 'Midnight Melodies', '07:51', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Bladderwort', 'Kendrick Lamar', 'Celestial Serenade', '09:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Singlewhorl Burrobrush', 'Beyoncé', 'Ephemeral Dreams', '03:48', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Parmotrema Lichen', 'Beyoncé', 'Serendipity Rhapsody', '02:53', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Ulunahele', 'Kendrick Lamar', 'Harmonic Whispers', '07:23', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Letrouitia Lichen', 'Beyoncé', 'Midnight Melodies', '03:12', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Cologania', 'Beyoncé', 'Enchanted Journey', '07:19', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Edwards'' Hole-in-the-sand Plant', 'Kendrick Lamar', 'Celestial Serenade', '07:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Rosemallow', 'Beyoncé', 'Midnight Melodies', '03:12', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Blue Ridge Bittercress', 'Adele', 'Enchanted Journey', '08:17', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hornemann''s Willowherb', 'Adele', 'Serendipity Rhapsody', '09:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Purpleosier Willow', 'Adele', 'Celestial Serenade', '06:30', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Variableleaf Collomia', 'Arctic Monkeys', 'Midnight Melodies', '08:32', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Dwarf Checkerbloom', 'The Weeknd', 'Midnight Melodies', '07:23', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Featherstem Clubmoss', 'Beyoncé', 'Midnight Melodies', '06:19', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sicklekeel Lupine', 'Beyoncé', 'Midnight Melodies', '08:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tall Trisetum', 'Kendrick Lamar', 'Enchanted Journey', '09:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hooker''s Townsend Daisy', 'The Weeknd', 'Celestial Serenade', '09:56', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Cottony Goldenaster', 'Adele', 'Enchanted Journey', '03:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Black Spruce', 'The Weeknd', 'Celestial Serenade', '03:40', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Lemon-flower Gum', 'The Weeknd', 'Serendipity Rhapsody', '04:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Blue Mountain Milkvetch', 'Beyoncé', 'Midnight Melodies', '03:23', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Eastern Prickly Gooseberry', 'Beyoncé', 'Enchanted Journey', '08:03', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Marumleaf Buckwheat', 'Adele', 'Serendipity Rhapsody', '05:11', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Showy Goldenrod', 'The Weeknd', 'Celestial Serenade', '07:38', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Thymeleaf Mock Orange', 'Beyoncé', 'Serendipity Rhapsody', '03:47', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sweet Pitcherplant', 'The Weeknd', 'Celestial Serenade', '08:33', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hairy Grama', 'Kendrick Lamar', 'Harmonic Whispers', '02:27', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Southwestern Cryptantha', 'Adele', 'Ephemeral Dreams', '05:37', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Coastal Bluff Bentgrass', 'The Weeknd', 'Harmonic Whispers', '05:18', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Leonard''s Beardtongue', 'Adele', 'Midnight Melodies', '04:55', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Bigseed Alfalfa Dodder', 'Beyoncé', 'Serendipity Rhapsody', '06:46', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Papillate Rinodina Lichen', 'Arctic Monkeys', 'Harmonic Whispers', '03:18', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hairy Knight''s-spur', 'Beyoncé', 'Serendipity Rhapsody', '09:42', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Little Spleenwort', 'Kendrick Lamar', 'Midnight Melodies', '06:07', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Pallid Suncup', 'Beyoncé', 'Serendipity Rhapsody', '05:28', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sphagnum', 'Kendrick Lamar', 'Enchanted Journey', '04:09', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Baton Rouge Blackberry', 'Arctic Monkeys', 'Celestial Serenade', '02:26', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Uralanguis', 'The Weeknd', 'Ephemeral Dreams', '07:09', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Flatstem Spikerush', 'Adele', 'Midnight Melodies', '08:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('White Rosinweed', 'Kendrick Lamar', 'Celestial Serenade', '08:04', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Western Bog Aster', 'The Weeknd', 'Midnight Melodies', '07:38', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Canadian White Violet', 'Beyoncé', 'Harmonic Whispers', '07:37', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Starch Grape Hyacinth', 'Kendrick Lamar', 'Enchanted Journey', '02:20', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('American Chickweed', 'Arctic Monkeys', 'Harmonic Whispers', '07:54', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Duchesne Rockcress', 'Adele', 'Enchanted Journey', '08:17', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Oldmaid Hawthorn', 'Kendrick Lamar', 'Harmonic Whispers', '07:06', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Physcomitrella Moss', 'The Weeknd', 'Midnight Melodies', '09:46', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Ornithostaphylos', 'The Weeknd', 'Enchanted Journey', '08:52', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Hybrid Rhododendron', 'Kendrick Lamar', 'Ephemeral Dreams', '05:16', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Spring Pygmycudweed', 'Arctic Monkeys', 'Midnight Melodies', '06:16', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Parry''s Lipfern', 'Arctic Monkeys', 'Celestial Serenade', '03:16', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Navajo Tea', 'Beyoncé', 'Enchanted Journey', '04:20', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Serrulate Penstemon', 'Kendrick Lamar', 'Harmonic Whispers', '08:39', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Oahu Pilo Kea', 'Adele', 'Celestial Serenade', '06:39', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Tall Coastal Plantain', 'The Weeknd', 'Midnight Melodies', '08:17', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Philonotis Moss', 'Beyoncé', 'Enchanted Journey', '03:12', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Reutealis', 'Beyoncé', 'Celestial Serenade', '08:44', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Smooth Baccharis', 'Beyoncé', 'Enchanted Journey', '03:46', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Littleleaf Brickellbush', 'Beyoncé', 'Enchanted Journey', '04:09', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Psorula Lichen', 'Arctic Monkeys', 'Midnight Melodies', '08:44', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Godfrey''s Sedge', 'The Weeknd', 'Enchanted Journey', '07:23', true) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Nevada Pea', 'Kendrick Lamar', 'Enchanted Journey', '07:20', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
insert into songs (name, artist, album, time, is_favorite) values ('Sea Lettuce', 'Arctic Monkeys', 'Ephemeral Dreams', '08:23', false) ON CONFLICT (NAME, ARTIST, ALBUM) DO NOTHING;
-- reduce the mock data set to groupings of artists with many songs on one album
delete from songs where id not in (
with cte as (
select array_agg(id) as ids, count(id) as len, artist, album from songs group by artist, album
)
select unnest(ids) from (
select *, DENSE_RANK() over (partition by artist order by len desc) as r from cte
) v where r =1
);